# remote_theme: abhinavs/moonwalk
# theme_config:
#   appearance: "dark"
#   appearance_toggle: true
#   show_description: true
#   show_footer: true

remote_theme: mmistakes/minimal-mistakes

title: JianHui (Jake) Li
description: Aspiring Data Scientist | Senior Major in CIS Data Analytics @ Baruch College
