remote_theme: mmistakes/jekyll-theme-basically-basic

lang: en-US
title: JianHui (Jake) Li
description: Aspiring Data Scientist | Senior Major in CIS Data Analytics @ Baruch College
github_username: JakeLi2001

