remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "dark"
locale: "en-US"
title: "JianHui (Jake) Li"
subtitle: "Aspiring Data Scientist"
repository: "JakeLi2001/JakeLi2001.github.io"

author:
  name: "JianHui (Jake) Li"
  avatar: "/assets/headshot.png"
  bio: "Aspiring Data Scientist, Senior majoring in CIS Data Analytics @ Baruch"
  location: "Brooklyn, NY"
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/JakeLi2001"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "www.linkedin.com/in/jakeli2001"

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/JakeLi2001"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "www.linkedin.com/in/jakeli2001"

include:
  - _pages
 
 # Defaults
defaults:
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
  
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

compress_html:
  clippings: all
  ignore:
    envs: development
