remote_theme: mmistakes/minimal-mistakes
plugins: 
- jekyll-include-cache
- jekyll-remote-theme
minimal_mistakes_skin: "dark"

title: JianHui (Jake) Li
description: Aspiring Data Scientist | Senior Major in CIS Data Analytics @ Baruch College
