remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "dark"
locale: "en-US"
title: "JianHui (Jake) Li"
subtitle: "Aspiring Data Scientist"
repository: "JakeLi2001/JakeLi2001.github.io"
name: *name "JianHui (Jake) Li"

author:
  name: *name
  avatar: /assets/headshot.png
  bio: "Aspiring Data Scientist, Senior majoring in CIS Data Analytics @ Baruch"
  location: "Brooklyn, NY"
  links:
    - label: "GitHub"
    - icon: "fab fa-fw fa-github"
    - url: "https://github.com/JakeLi2001"

include:
  - _pages
  
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
